add api tests
dziana-babrova/Api-tests pull request #1
Opened 2022-09-20 18:20 UTC by dziana-babrova

2022-09-20 19:14 UTC, rimus requested changes

2022-09-20 19:14 UTC, rimus commented on tests/get-scenario.js
> +});
I hope these sections should be inside describe :) Please check whole PR.

2022-09-20 19:14 UTC, rimus commented on tests/post-scenario.js
> +    chai.expect(response.data.id).to.exist;
Format the code.

2022-09-23 08:46 UTC, dziana-babrova commented on tests/post-scenario.js
> +    chai.expect(response.data.id).to.exist;
fixed

2022-09-29 10:51 UTC, rimus approved these changes
Looks good.

2022-09-29 10:52 UTC, merged